image: golang:1.9

build:
  script: |
    apt-get update
    apt-get -y install zip
    mkdir -p /go/src/github.com/crankykernel
    cp -a . /go/src/github.com/crankykernel/ctrader
    cd /go/src/github.com/crankykernel/ctrader
    go get -u github.com/golang/dep/cmd/dep
    dep ensure -v
    go build -v

    make dist
    cp dist/*.zip ${CI_PROJECT_DIR}

  artifacts:
    paths:
      - "*.zip"

